'use client'

import { useState } from 'react'
import { Check, ShieldCheck } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

export function SettingsView() {
  const [saved, setSaved] = useState(false)
  const [alerts, setAlerts] = useState({ critical: true, digest: true, confidence: false })
  return <div className="grid gap-6 lg:grid-cols-[1fr_320px]"><section className="surface p-5 sm:p-6"><h2 className="section-title">Workspace profile</h2><p className="mt-1 text-xs text-slate-500">Used in briefs, exports, and comparative baselines.</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><label><span className="mb-2 block text-xs font-medium text-slate-600">Workspace name</span><Input defaultValue="Nova Commerce" /></label><label><span className="mb-2 block text-xs font-medium text-slate-600">Industry</span><Input defaultValue="E-commerce" /></label><label><span className="mb-2 block text-xs font-medium text-slate-600">Timezone</span><Input defaultValue="Asia/Kolkata (IST)" /></label><label><span className="mb-2 block text-xs font-medium text-slate-600">Weekly baseline</span><Input defaultValue="Previous 7 days" /></label></div><div className="mt-6 border-t pt-5"><Button onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 1700) }}>{saved ? <><Check size={14} />Saved</> : 'Save changes'}</Button></div></section><aside className="space-y-6"><section className="surface p-5"><h2 className="section-title">Alerts</h2><div className="mt-4 space-y-4"><Toggle label="Critical issue alerts" description="Notify when volume or severity spikes." checked={alerts.critical} onChange={() => setAlerts({ ...alerts, critical: !alerts.critical })} /><Toggle label="Daily CX brief" description="Send at 9:00 AM each day." checked={alerts.digest} onChange={() => setAlerts({ ...alerts, digest: !alerts.digest })} /><Toggle label="Low-confidence flags" description="Surface clusters below 85%." checked={alerts.confidence} onChange={() => setAlerts({ ...alerts, confidence: !alerts.confidence })} /></div></section><section className="rounded-xl border border-emerald-200 bg-emerald-50 p-5"><ShieldCheck size={18} className="text-emerald-700" /><p className="mt-3 text-sm font-semibold text-emerald-950">Demo data only</p><p className="mt-1 text-xs leading-5 text-emerald-800">All conversations in this workspace are synthetic and stored locally.</p></section></aside></div>
}

function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: () => void }) { return <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-slate-700">{label}</p><p className="mt-0.5 text-[10px] leading-4 text-slate-500">{description}</p></div><button role="switch" aria-checked={checked} onClick={onChange} className={`relative h-5 w-9 shrink-0 rounded-full transition ${checked ? 'bg-emerald-500' : 'bg-slate-200'}`}><span className={`absolute top-0.5 h-4 w-4 rounded-full bg-white shadow-sm transition ${checked ? 'left-[18px]' : 'left-0.5'}`} /></button></div> }
